2011/12/10 01:24:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(86): CModule->getComponent('db')
#4 C:\xampp\htdocs\YiiRoot\framework\gii\generators\model\ModelCode.php(54): CModule->__get('db')
#5 C:\xampp\htdocs\YiiRoot\framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\YiiRoot\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(277): CController->run('')
#13 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(136): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\globaldebtmgm\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/globaldebtmgm/index.php?r=gii/model
2011/12/10 01:24:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(86): CModule->getComponent('db')
#4 C:\xampp\htdocs\YiiRoot\framework\gii\generators\model\ModelCode.php(54): CModule->__get('db')
#5 C:\xampp\htdocs\YiiRoot\framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\YiiRoot\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(277): CController->run('')
#13 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(136): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\globaldebtmgm\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/globaldebtmgm/index.php?r=gii/model
2011/12/10 01:35:01 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'globaldebtmgm.tbl_debtor_negotiator' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `tbl_debtor_negotiator`.
in C:\xampp\htdocs\globaldebtmgm\index.php (13)
2011/12/10 01:35:41 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'globaldebtmgm.tbl_progam_infor' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `tbl_progam_infor`.
in C:\xampp\htdocs\globaldebtmgm\index.php (13)
2011/12/10 01:35:53 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'globaldebtmgm.tbl_program_infor' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `tbl_program_infor`.
in C:\xampp\htdocs\globaldebtmgm\index.php (13)
2011/12/10 01:39:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/debtor".' in C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(136): CWebApplication->runController('gii/debtor')
#1 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\globaldebtmgm\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/globaldebtmgm/index.php?r=gii/debtor
